# action.yml
name: Swagger Editor Validator
description: This GitHub Actions validates OpenAPI (OAS) definition file using Swagger Editor.
inputs:
  swagger-editor-url:
    description: URL where Swagger Editor is served
    required: false
    default: https://editor.swagger.io/
  definition-file:
    description: Path to definition file
    required: true
  ignore-error:
    description: JavaScript file containing predicate for determining if the error should be ignored or not
    required: false
  default-timeout:
    description: Maximum time in milliseconds a script waits for certain actions or events to occur
    required: false
runs:
  using: composite
  steps:
    - run: cd ${{ github.action_path }} && npm install
      shell: bash
    - run: cd ${{ github.action_path }} && SWAGGER_EDITOR_URL=${{ inputs.swagger-editor-url }} DEFINITION_FILE=${{ inputs.definition-file }} IGNORE_ERROR=${{ inputs.ignore-error }} DEFAULT_TIMEOUT=${{ inputs.default-timeout }} node src/index.js
      shell: bash
branding:
  icon: 'file-text'
  color: 'green'
